language: generic
sudo: required
services:
  - docker

before_install:
  - docker build -t anasim016/docker-react -f Dockerfile.dev .

script:
  - docker run -e CI=true anasim016/docker-react npm run test
